# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: frekele/java:jdk8u152

pipelines:
  default:
  - step:
      caches:
      - gradle
      script: # Modify the commands below to build your repository.
      # You must commit the Gradle wrapper to your repository
      # https://docs.gradle.org/current/userguide/gradle_wrapper.html -x check

      # - bash ./gradlew aCiVersion
      - bash ./gradlew build -info

      # - bash ./gradlew sonarqube --debug -Dsonar.projectKey=Apertum_qsystem -Dsonar.organization=apertum-bitbucket -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      # - bash ./gradlew sonarqube --info

      # - bash ./gradlew copylib
      # - bash ./gradlew izPackCreateInstaller
      # - bash ./gradlew bzipCi

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    node-scanner: ~/.sonar/native-sonar-scanner